name: Build and Deploy to FTP

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Install Frontend dependencies
        run: cd frontend && npm install --legacy-peer-deps
        
      - name: Install Backend dependencies
        run: cd backend && npm install
        
      - name: Build Frontend
        run: cd frontend && npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max_old_space_size=4096"
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
          REACT_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
          REACT_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          
      - name: Deploy Frontend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: rubyet.info
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./frontend/build/
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode/**
            **/README.md
            
      - name: Deploy Backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: rubyet.info
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./backend/
          server-dir: ./backend/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode/**
            **/README.md
            **/.env
            **/data/**
            
      - name: Deployment Success Notification
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🚀 Your portfolio is now live!"
          echo "📊 Frontend build size: $(du -sh frontend/build 2>/dev/null | cut -f1 || echo 'N/A')"
          echo "📦 Backend deployed to /backend/"
          echo "⚠️  Remember to:"
          echo "   1. Run 'npm install' in the backend folder on your server"
          echo "   2. Set up environment variables (.env) on your server"
          echo "   3. Start the backend server (node server.js or use PM2)"
          
      - name: Deployment Failed Notification
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the logs above for errors"
